require('dotenv').config();
const mongoose = require('mongoose');
const connectDB = require('./config/db');
const Job = require('./models/Job');
const User = require('./models/User');

const jobsData = [
  {
    title: 'Senior Full Stack Developer',
    company: 'TechCorp Solutions',
    description: 'We are looking for an experienced Full Stack Developer to join our growing team. You will work on cutting-edge web technologies and collaborate with a talented team of engineers.',
    requirements: ['5+ years experience', 'React/Node.js', 'MongoDB', 'AWS', 'Git'],
    location: 'Delhi, India',
    jobType: 'Full-time',
    salary: { min: 120000, max: 160000, currency: 'USD' },
    experience: 'Senior Level',
    skills: ['JavaScript', 'React', 'Node.js', 'MongoDB', 'AWS', 'Docker'],
    status: 'open',
  },
  {
    title: 'Frontend Developer',
    company: 'Digital Innovations Inc',
    description: 'Join our frontend team to build beautiful and responsive user interfaces. We use modern React and next-gen web technologies.',
    requirements: ['3+ years experience', 'React', 'CSS/SCSS', 'JavaScript'],
    location: 'Mumbai, India',
    jobType: 'Full-time',
    salary: { min: 90000, max: 130000, currency: 'USD' },
    experience: 'Mid Level',
    skills: ['React', 'JavaScript', 'CSS', 'Redux', 'REST APIs'],
    status: 'open',
  },
  {
    title: 'Backend Developer',
    company: 'CloudBase Systems',
    description: 'We need a skilled backend developer to build scalable server-side applications. Experience with microservices is a plus.',
    requirements: ['4+ years experience', 'Node.js/Java', 'SQL/NoSQL', 'REST APIs', 'Microservices'],
    location: 'Kolkata, India',
    jobType: 'Full-time',
    salary: { min: 100000, max: 145000, currency: 'USD' },
    experience: 'Mid Level',
    skills: ['Node.js', 'Java', 'Python', 'PostgreSQL', 'MongoDB', 'Docker'],
    status: 'open',
  },
  {
    title: 'Junior Web Developer',
    company: 'StartupHub',
    description: 'Great opportunity for junior developers to learn and grow. We provide mentorship and exciting projects.',
    requirements: ['1+ years experience', 'HTML/CSS/JavaScript', 'Basic React knowledge'],
    location: 'Remote',
    jobType: 'Full-time',
    salary: { min: 50000, max: 70000, currency: 'USD' },
    experience: 'Entry Level',
    skills: ['HTML', 'CSS', 'JavaScript', 'React', 'Git'],
    status: 'open',
  },
  {
    title: 'DevOps Engineer',
    company: 'Infrastructure Pro',
    description: 'Help us manage and optimize our cloud infrastructure. We use AWS, Docker, and Kubernetes.',
    requirements: ['5+ years DevOps', 'AWS/GCP', 'Docker/Kubernetes', 'CI/CD'],
    location: 'Banglore,India',
    jobType: 'Full-time',
    salary: { min: 110000, max: 150000, currency: 'USD' },
    experience: 'Senior Level',
    skills: ['AWS', 'Docker', 'Kubernetes', 'CI/CD', 'Linux', 'Terraform'],
    status: 'open',
  },
  {
    title: 'Data Scientist',
    company: 'AI Analytics Ltd',
    description: 'Work on machine learning models and data analysis projects. We process billions of data points daily.',
    requirements: ['3+ years experience', 'Python', 'ML frameworks', 'SQL'],
    location: 'Chennai,India',
    jobType: 'Full-time',
    salary: { min: 100000, max: 160000, currency: 'USD' },
    experience: 'Mid Level',
    skills: ['Python', 'Machine Learning', 'TensorFlow', 'SQL', 'Statistics', 'Pandas'],
    status: 'open',
  },
  {
    title: 'Mobile App Developer',
    company: 'AppStudio Creative',
    description: 'Develop iOS and Android applications. Experience with React Native or Flutter required.',
    requirements: ['3+ years mobile development', 'React Native/Flutter', 'iOS/Android'],
    location: 'Hyderabad,India',
    jobType: 'Full-time',
    salary: { min: 85000, max: 125000, currency: 'USD' },
    experience: 'Mid Level',
    skills: ['React Native', 'iOS', 'Android', 'JavaScript', 'Objective-C', 'Swift'],
    status: 'open',
  },
  {
    title: 'UI/UX Designer',
    company: 'Design Studio 360',
    description: 'Create amazing user experiences for web and mobile applications. Figma and prototyping skills required.',
    requirements: ['3+ years experience', 'Figma/Sketch', 'User Research', 'Prototyping'],
    location: 'Lucknow,India',
    jobType: 'Full-time',
    salary: { min: 75000, max: 110000, currency: 'USD' },
    experience: 'Mid Level',
    skills: ['Figma', 'UI Design', 'UX Research', 'Prototyping', 'Adobe XD'],
    status: 'open',
  },
  {
    title: 'QA Engineer',
    company: 'Quality First Testing',
    description: 'Ensure software quality through automated and manual testing. We use Selenium and Jest.',
    requirements: ['2+ years QA experience', 'Test Automation', 'Selenium/Jest', 'SQL'],
    location: 'Ahmedabad,India',
    jobType: 'Full-time',
    salary: { min: 60000, max: 90000, currency: 'USD' },
    experience: 'Entry Level',
    skills: ['Selenium', 'Jest', 'Test Automation', 'SQL', 'Python'],
    status: 'open',
  },
  {
    title: 'Database Administrator',
    company: 'DataCore Systems',
    description: 'Manage and maintain large-scale database systems. Performance tuning and security are key responsibilities.',
    requirements: ['5+ years DBA', 'PostgreSQL/MySQL', 'Backup/Recovery', 'Performance Tuning'],
    location: 'Ranchi,India',
    jobType: 'Full-time',
    salary: { min: 95000, max: 140000, currency: 'USD' },
    experience: 'Senior Level',
    skills: ['PostgreSQL', 'MySQL', 'MongoDB', 'Database Design', 'Performance Tuning'],
    status: 'open',
  },
  {
    title: 'Solutions Architect',
    company: 'Enterprise Tech Solutions',
    description: 'Design and implement large-scale technology solutions for enterprise clients.',
    requirements: ['7+ years experience', 'System Design', 'Cloud Architecture', 'Enterprise Software'],
    location: 'Delhi,India',
    jobType: 'Full-time',
    salary: { min: 130000, max: 180000, currency: 'USD' },
    experience: 'Executive',
    skills: ['System Architecture', 'AWS', 'Azure', 'Enterprise Design', 'Project Management'],
    status: 'open',
  },
  {
    title: 'React Developer',
    company: 'WebFlow Studios',
    description: 'Build dynamic web applications using React. Experience with hooks and state management required.',
    requirements: ['2+ years React', 'Redux/Context', 'REST APIs', 'Jest'],
    location: 'Chandigarh,India',
    jobType: 'Full-time',
    salary: { min: 80000, max: 120000, currency: 'USD' },
    experience: 'Mid Level',
    skills: ['React', 'Redux', 'JavaScript', 'CSS', 'REST APIs', 'Jest'],
    status: 'open',
  },
  {
    title: 'Node.js Developer',
    company: 'Backend Masters',
    description: 'Develop robust backend services using Node.js and Express. Async programming expertise needed.',
    requirements: ['3+ years Node.js', 'Express', 'MongoDB', 'REST APIs'],
    location: 'Remote',
    jobType: 'Full-time',
    salary: { min: 85000, max: 125000, currency: 'USD' },
    experience: 'Mid Level',
    skills: ['Node.js', 'Express', 'MongoDB', 'REST APIs', 'JavaScript'],
    status: 'open',
  },
  {
    title: 'Python Developer',
    company: 'Data Solutions Corp',
    description: 'Write efficient Python code for data processing and web applications. Django/FastAPI experience preferred.',
    requirements: ['2+ years Python', 'Django/FastAPI', 'SQL', 'Git'],
    location: 'Chennai,India',
    jobType: 'Full-time',
    salary: { min: 80000, max: 120000, currency: 'USD' },
    experience: 'Mid Level',
    skills: ['Python', 'Django', 'FastAPI', 'SQL', 'REST APIs'],
    status: 'open',
  },
  {
    title: 'Java Developer',
    company: 'Enterprise Java Inc',
    description: 'Develop enterprise applications using Java. Spring Framework and microservices experience needed.',
    requirements: ['4+ years Java', 'Spring Boot', 'Microservices', 'SQL'],
    location: 'Banglore,India',
    jobType: 'Full-time',
    salary: { min: 95000, max: 135000, currency: 'USD' },
    experience: 'Mid Level',
    skills: ['Java', 'Spring Boot', 'Microservices', 'SQL', 'Maven'],
    status: 'open',
  },
  {
    title: 'Technical Lead',
    company: 'Tech Innovation Labs',
    description: 'Lead a team of developers and architect technical solutions. Mentorship skills essential.',
    requirements: ['6+ years experience', 'Team Leadership', 'System Design', 'Code Review'],
    location: 'Hyderabad,India',
    jobType: 'Full-time',
    salary: { min: 125000, max: 170000, currency: 'USD' },
    experience: 'Senior Level',
    skills: ['Leadership', 'System Design', 'Code Review', 'Mentoring', 'Architecture'],
    status: 'open',
  },
  {
    title: 'Security Engineer',
    company: 'CyberGuard Systems',
    description: 'Identify and fix security vulnerabilities. Penetration testing and security audits required.',
    requirements: ['4+ years security', 'Penetration Testing', 'Network Security', 'OWASP'],
    location: 'Chandigarh,India',
    jobType: 'Full-time',
    salary: { min: 105000, max: 150000, currency: 'USD' },
    experience: 'Senior Level',
    skills: ['Security', 'Penetration Testing', 'Network Security', 'Cryptography'],
    status: 'open',
  },
  {
    title: 'Cloud Architect',
    company: 'Cloud Innovations',
    description: 'Design cloud infrastructure and migration strategies. AWS and GCP expertise needed.',
    requirements: ['5+ years cloud', 'AWS/GCP', 'Kubernetes', 'Infrastructure as Code'],
    location: 'Mumbai,India',
    jobType: 'Full-time',
    salary: { min: 120000, max: 160000, currency: 'USD' },
    experience: 'Senior Level',
    skills: ['AWS', 'GCP', 'Kubernetes', 'Terraform', 'Docker'],
    status: 'open',
  },
  {
    title: 'Graphic Designer',
    company: 'Creative Studios',
    description: 'Design marketing materials and brand assets. Proficiency in Adobe Suite required.',
    requirements: ['2+ years experience', 'Adobe Creative Suite', 'Brand Guidelines', 'Print Design'],
    location: 'Lucknow,India',
    jobType: 'Full-time',
    salary: { min: 60000, max: 90000, currency: 'USD' },
    experience: 'Entry Level',
    skills: ['Adobe Photoshop', 'Illustrator', 'InDesign', 'Brand Design'],
    status: 'open',
  },
  {
    title: 'Project Manager',
    company: 'Project Excellence Ltd',
    description: 'Manage software development projects. Agile/Scrum experience required.',
    requirements: ['3+ years PM', 'Agile/Scrum', 'Jira', 'Risk Management'],
    location: 'Remote',
    jobType: 'Full-time',
    salary: { min: 75000, max: 110000, currency: 'USD' },
    experience: 'Mid Level',
    skills: ['Project Management', 'Agile', 'Scrum', 'Jira', 'Leadership'],
    status: 'open',
  },
  {
    title: 'Business Analyst',
    company: 'Strategy & Analytics',
    description: 'Analyze business requirements and translate to technical specifications.',
    requirements: ['2+ years BA', 'Requirements Analysis', 'SQL', 'Data Analysis'],
    location: 'Hyderabad,India',
    jobType: 'Full-time',
    salary: { min: 70000, max: 105000, currency: 'USD' },
    experience: 'Mid Level',
    skills: ['Business Analysis', 'SQL', 'Data Analysis', 'Tableau', 'Requirements Gathering'],
    status: 'open',
  },
  {
    title: 'Software Engineer Intern',
    company: 'TechStarts Inc',
    description: 'Perfect for recent graduates or career changers. Learn from experienced mentors.',
    requirements: ['Basic programming', 'JavaScript/Python', 'Problem Solving'],
    location: 'Remote',
    jobType: 'Internship',
    salary: { min: 20000, max: 35000, currency: 'USD' },
    experience: 'Entry Level',
    skills: ['JavaScript', 'Problem Solving', 'Team Work', 'Learning Mindset'],
    status: 'open',
  },
  {
    title: 'DevOps Intern',
    company: 'CloudMinds',
    description: 'Learn DevOps practices in a supportive environment. No prior experience needed.',
    requirements: ['Linux basics', 'Eagerness to learn', 'Problem solving'],
    location: 'Remote',
    jobType: 'Internship',
    salary: { min: 18000, max: 30000, currency: 'USD' },
    experience: 'Entry Level',
    skills: ['Linux', 'Docker basics', 'Learning', 'Collaboration'],
    status: 'open',
  },
  {
    title: 'Contract Developer',
    company: 'Freelance Projects Co',
    description: '3-month contract to build custom web application. Flexible hours.',
    requirements: ['2+ years experience', 'Full Stack', 'Self-motivated'],
    location: 'Remote',
    jobType: 'Contract',
    salary: { min: 60000, max: 90000, currency: 'USD' },
    experience: 'Mid Level',
    skills: ['Full Stack Development', 'Self-management', 'Communication'],
    status: 'open',
  },
  {
    title: 'Part-time PHP Developer',
    company: 'WebDev Partners',
    description: '20 hours/week. Maintain WordPress sites and custom PHP applications.',
    requirements: ['2+ years PHP', 'WordPress', 'MySQL'],
    location: 'Remote',
    jobType: 'Part-time',
    salary: { min: 30000, max: 50000, currency: 'USD' },
    experience: 'Entry Level',
    skills: ['PHP', 'WordPress', 'MySQL', 'HTML/CSS'],
    status: 'open',
  },
  {
    title: 'Temporary Support Engineer',
    company: 'Tech Support Plus',
    description: '2-month temporary position. Support technical issues and customer queries.',
    requirements: ['Support experience', 'Troubleshooting', 'Communication'],
    location: 'Ranchi,India',
    jobType: 'Temporary',
    salary: { min: 35000, max: 50000, currency: 'USD' },
    experience: 'Entry Level',
    skills: ['Technical Support', 'Troubleshooting', 'Customer Service'],
    status: 'open',
  },
  {
    title: 'Machine Learning Engineer',
    company: 'AI Forward',
    description: 'Build ML models and deploy them to production. TensorFlow/PyTorch required.',
    requirements: ['3+ years ML', 'TensorFlow/PyTorch', 'Python', 'Deep Learning'],
    location: 'Kolkata,India',
    jobType: 'Full-time',
    salary: { min: 120000, max: 170000, currency: 'USD' },
    experience: 'Senior Level',
    skills: ['Machine Learning', 'Deep Learning', 'Python', 'TensorFlow', 'PyTorch'],
    status: 'open',
  },
  {
    title: 'Go Developer',
    company: 'Performance Systems',
    description: 'Build high-performance backend systems using Go. Concurrency expertise required.',
    requirements: ['3+ years Go', 'Concurrency', 'REST APIs', 'Microservices'],
    location: 'Ahmedabad,India',
    jobType: 'Full-time',
    salary: { min: 100000, max: 145000, currency: 'USD' },
    experience: 'Mid Level',
    skills: ['Go', 'Concurrency', 'REST APIs', 'Microservices', 'Docker'],
    status: 'open',
  },
  {
    title: 'Rust Developer',
    company: 'Systems Software Ltd',
    description: 'Develop system-level software using Rust. Performance and memory safety critical.',
    requirements: ['2+ years Rust', 'Systems Programming', 'Performance Optimization'],
    location: 'Remote',
    jobType: 'Full-time',
    salary: { min: 110000, max: 155000, currency: 'USD' },
    experience: 'Mid Level',
    skills: ['Rust', 'Systems Programming', 'Performance', 'Low-level Programming'],
    status: 'open',
  },
  {
    title: 'Angular Developer',
    company: 'Enterprise Web Apps',
    description: 'Build enterprise web applications with Angular. TypeScript expertise required.',
    requirements: ['3+ years Angular', 'TypeScript', 'RxJS', 'REST APIs'],
    location: 'Banglore,India',
    jobType: 'Full-time',
    salary: { min: 90000, max: 130000, currency: 'USD' },
    experience: 'Mid Level',
    skills: ['Angular', 'TypeScript', 'RxJS', 'REST APIs', 'HTML/CSS'],
    status: 'open',
  },
  {
    title: 'Vue.js Developer',
    company: 'Modern Web Solutions',
    description: 'Develop progressive web apps using Vue.js. Composition API experience preferred.',
    requirements: ['2+ years Vue.js', 'JavaScript', 'REST APIs', 'Git'],
    location: 'Ranchi,India',
    jobType: 'Full-time',
    salary: { min: 85000, max: 125000, currency: 'USD' },
    experience: 'Mid Level',
    skills: ['Vue.js', 'JavaScript', 'CSS', 'REST APIs', 'Webpack'],
    status: 'open',
  },
];

const seedJobs = async () => {
  try {
    console.log('🌱 Starting job seeding...');
    await connectDB();
    
    // Get a user to associate with jobs
    let user = await User.findOne();
    
    if (!user) {
      console.log('⚠️  No users found. Creating a default employer user...');
      user = await User.create({
        firstName: 'Admin',
        lastName: 'Employer',
        email: 'admin@employer.com',
        phone: '+1-555-0100',
        password: 'admin123456',
        userType: 'employer',
      });
      console.log('✅ Default employer user created');
    }
    
    // Clear existing jobs
    await Job.deleteMany({});
    console.log('🗑️  Cleared existing jobs');
    
    // Add postedBy to each job
    const jobsWithUser = jobsData.map(job => ({
      ...job,
      postedBy: user._id,
    }));
    
    // Insert jobs
    await Job.insertMany(jobsWithUser);
    console.log(`✅ Successfully added 30 jobs to the database!`);
    
    // Show summary
    const totalJobs = await Job.countDocuments();
    console.log(`📊 Total jobs in database: ${totalJobs}`);
    
    process.exit(0);
  } catch (error) {
    console.error('❌ Seeding error:', error.message);
    process.exit(1);
  }
};

seedJobs();
